version: "3.8"

services:
  postgres6:
    image: postgres:14
    container_name: attendance-postgres
    environment:
      POSTGRES_DB: attendance_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    ports:
      - "5490:5432"
    volumes:
      - attendance_db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    container_name: attendance-backend
    ports:
      - "3080:3080"
    depends_on:
      - postgres6
    environment:
      - PGHOST=postgres6
      - PGUSER=postgres
      - PGPASSWORD=admin123
      - PGDATABASE=attendance_db
      - PGPORT=5432
    restart: unless-stopped

  employee-attendance:
    build:
      context: ./Employee-attendance
    container_name: attendance-employee-ui
    ports:
      - "8701:80"
    depends_on:
      - backend
    restart: unless-stopped

  hr-attendance:
    build:
      context: ./HR-attendance
    container_name: attendance-hr-ui
    ports:
      - "8801:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  attendance_db_data:

